//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_Web_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public Kullanicilar()
        {
            this.CihazEkles = new HashSet<CihazEkle>();
            this.KanalEkles = new HashSet<KanalEkle>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public string Rol { get; set; }
        public System.DateTime AbonelikTarih { get; set; }
        public Nullable<int> SirketEkleId { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual SirketEkle SirketEkle { get; set; }
        public virtual ICollection<CihazEkle> CihazEkles { get; set; }
        public virtual ICollection<KanalEkle> KanalEkles { get; set; }
    }
}
