//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_Web_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SirketEkle
    {
        public SirketEkle()
        {
            this.Kullanicilars = new HashSet<Kullanicilar>();
            this.CihazEkles = new HashSet<CihazEkle>();
            this.KanalEkles = new HashSet<KanalEkle>();
        }
    
        public int Id { get; set; }
        public string SirketIsim { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
        public virtual ICollection<CihazEkle> CihazEkles { get; set; }
        public virtual ICollection<KanalEkle> KanalEkles { get; set; }
    }
}
